apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: weather-app
spec:
 selector:
   # Selector for Pods
   app: weather-app
 ports:
   # Port Map
 - port: 80
   targetPort: 5004
   protocol: TCP
 type: LoadBalancer