pipeline:
  identifier: Build_weather_app_example_1697104169258
  name: Build weather-app-example
  orgIdentifier: default
  projectIdentifier: weather
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1697103494549
        repoName: weather-app-example
  stages:
    - stage:
        identifier: build
        name: Build and Test
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
              - step:
                  type: Run
                  name: Run_3
                  identifier: Run_3
                  spec:
                    shell: Sh
                    command: |-
                      npm install
                      npm test
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
        type: CI
